sudo: required
language: java
services:
- docker
jdk: openjdk11
cache:
  directories:
  - $HOME/.m2
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::7}
  - secure: WiJpBY0BWpsSyLGDQ84cRIOItwZ5OCcFD9X5gjj82jVdfORuy+2YilqC0VGjWeW3JGeK1O1sL8VSkJtQ+Ff9TGT5r9BNEHdlwOPV2xruxEt6Kt3Q7TDHgA6g5x3oblIBHHoAdUy3fVZTDwZEpRx8vnz+svYBEU/O378B9vqOYRUHW/Ipte7eJcN0t2rXjfUxSREX0J95ID2S6807oHgPie8FuHjlzN1wiRrGkiiTyUFATIWPzpHUfml9HpjMx8Nx4BX0g/Mi53DMejtxyDtR3/YpeYwxK5UjYf/zT/MpSRfb7C1grNSBHnn/qCHscWi68/GGvNArDJ1UHaQyZpLRAoTKzb6PC2hR4ttp2vJP+tHFhD2wkFKpp4nv51zSPGLy/jRRp74AeSoK3auAFlg1TJSStS6aA+O+nMCta4HPud1UEknlIVAS8lqxcSQd8SpxhXMwWjQ1Xo57C8yCTGJtcLFyrOeiUw7993rwybEdsFcWST31BqL4LnKkBCTuLbPkQK5rS9KH6H5LRR3T/fVDk6m+DW8OyqQ/+0p0PNdltn/lPncOFztY5+HN8TRERfxZ9EgK01RK6uJh8v5NhpcnUfj+HvH6qE9koItJTyB1wYiZkCBOfjB4dEFOOIsORC0eXLjM3xLxmj8nqyyzutrz3m5HS1RI5coc0nbz9L4RtzA=
  - secure: TrdesjBLOMC9yfCXsyWYQgvuvtE49iYOEP/GstluXyPemhTYMMLu76KeTcGyeo7jL//YMXsCRBaaioY5y8iDGPCCfYVQUcl39w/5jLc7A7Qxp+IeCV9wESHvimlrgBpes1l1prIN0/ZtC2pKL47FhK43Stoulg1x++MkCi0YRUuBSXsU43Z/N1u3ooRWlLmBtfrOa6runFOPi3JWGiU23Yqe5l+HcHxGgV/p4QTfGvQYhWcZBoJLlosJQxWkeOhdDTIfejJ9zG4gv7G4PFMpuUY+/DcJnjOx5WRHc5e2UyVsBUSjxKXyEPV+CeOxIv7QNmUOVPbWj9Ez/jOSqhm2tYKFOORcYgL1rP8OYoO+ChZi5dGyfZbSEgV+oiW7SVg4RDfzwbgiHuebswGmozDR+L2JkfCRQY6mLfJ6qid+FMz+ORqw+AfCNbbU3+H7VCMRO7wMDmHS9TqHGyfaye0fXLKda/Wh7akuC9xCrr/heDfcT6mRN0/JvVCWLL1M3ocVMUBxdquPvxtbbMnDdz2meVWPy5Yy7faHaLRIEyWvY3JB1wi6aU72imViWePJIsy37JqoPake0mYRbgtRNYttO6KbWluHHiwM3MsWbqQs9LgrdXsEefOvDKUmRLW278ThKChucXAJ8IkyglHqZE+0zl6qqQSOUi/gdUX2U1qUGEU=
  - secure: gcBDhdjwck4IrU5PIEuNbCUYnaiUyYh34F5Hw8KabW1nQvCjYxi12Uojpe2FM4KpoNd2oc4fo/NksXBWGYtkiBJigOCBybLQVV4kbsIg1NJ/v5+nze1mhYe0dzJMx6EmhEnOmWTRqyDPJOiptDtOWBk6KqrF19zprXzhlo8rjr2h3yJk0uox70i8d8whGNsjLgYLlA+BjXX2t60je6ODCCX48Jjf23Lq2vYPvn7LUg8E+dFmxYbisE75ea+3/z+NhV3YoGmj1f+Iv2h+6v8uIP6HaSTnCAX80eXmPr9VB9dM55H1zJnSV3FOpaOcX3fc1os8qLS+Ht1zt8pIvJc0+EjwU8HNK8g2ad17ZNqxiAD28GixSdbi8COdelvtwK+cMW5fKTMo7A3jQQux2H61bF6GSvNtCbBiaf9ljZDxqxObB2NTh82ruw15legbtIsJUO3ZcYIdtVgNrIjYsBt8AOj0Gh70va/BxvlliMf/UEJhnH12slWiw5eWAjk4hxaxvsLyK46hljSCwsQPIsDKL1ZeA4ZUyYh7ahlH7cl5VH2S1Mm1rmddg29o1un7FBwfBFwRof1OfksKD+qv9FrsUWKIrHJjr4j0GugFRI6SVkBO3vc7OhrVWSfgEbTnQab7Cp+360X8qOzSfnLkl2NBmcoJiQRNrfdwNfoPigVp5lU=
jobs:
  include:
  - stage: test
    script: "mvn test"
    after_success:
    - bash <(curl -s https://codecov.io/bash)
  - stage: production build
    script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
    - export REPO=localmotion/smokefree-initiative-service
    - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo
      $TRAVIS_BRANCH | sed 's/\//_/g' ; fi`
    - docker build -f Dockerfile -t $REPO:$COMMIT .
    - docker tag $REPO:$COMMIT $REPO:$TAG
    - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
    - docker push $REPO
notifications:
  slack:
    rooms:
      secure: XVE83a8kms/EyJoQLxf2hbj/4EsHmLXMnUgNnbEhP4pwqmUGJtmA75sSC/2CxFUb0Iel29QmxywbywuKKhYRlG5VYppdipAz6hwfAQLIcxuBAOxNOxG4eEPbqdUtvWtlZ8yDymgBywX5slnkhHCwagS3E05R+aNfCQ6DprL1SlVtwnlZQME8cKlSGVXVxfpQ1l3gFTavoU68iwIdq8LwLGUai/zeDo1WzEhP/OhV77HRCkTMRyigAhD/Bz3+E1hlU6lH0y1Bkqn2zo8Udize/JBRJMZYRkAvwCpgDZNMgTr+9SVSsDPyHOdTbDz3mQGwkZDFsG702DUEyHLr/xV7v0B2TDqKBfD5hCsdOg84wE3cHqqZwQwMsF+vZNXp8YzzkW1ikSVvo+qGYFUlqvFYzz9dRG7QStA4D+dS+YQRF89qmqadEOlZs7QbmIPr8bt8lHLlgUvunYqlgOWcbKb1n0IC2vYjiiFj3eunxOoo39/C5yY6+60yT4BYSE2pFamvRyKl+BFLhlIxZ2zyHhNxUBDqfTNz7VO2JHtCxaF2xOlhdCX1nfLF2t+OOy3N782lCjOwXka8j7OeU7Am7oC6cAQmUduhEbynyd/j9J6DIPrGsegKBvPMW/iBu0sq56GpPchDXXNbCPXmnFV947F6944MTXnc2FnheGcRlcoVUVc=
    on_success: always
    on_failure: always
