micronaut:
  server:
    port: 18086
    cors:
      enabled: true
#      configurations:
#        web:
#          allowedOrigins:
#          - *
#      - http://foo.com
#      - ^http(|s)://www\.google\.com$

  router:
    # IMPORTANT:
    # When moving from Micronaut M4 to 1.0, this configuration will likely break
    # See https://github.com/micronaut-projects/micronaut-core/commit/72cc492e317027189836933f02330bf9f65ed453#diff-81426fb3a435372472dd5e40424e69c2L44
    static:
      resources:
        enabled: true
        paths: classpath:public
        mapping: /**
  application:
    name: smokefree-initiative-service
  security:
    enabled: true
    endpoints:
      login:
        enabled: true
      oauth:
        enabled: true
    token:
      jwt:
        enabled: true
        signatures:
          secret:
            generator:
              secret: "${JWT_GENERATOR_SIGNATURE_SECRET:b04dc560-e955-49e8-9f74-e72a5d34b160}"
## SSL probably not necessary since it's transparently handled by Istio
#  ssl:
#    enabled: true
#    buildSelfSigned: true
---
mongodb:
    uri: "mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}"
---
redis:
    uri: redis://localhost
---
tracing:
  jaeger:
    enabled: true
    sampler:
      probability: 0.1
---
# https://docs.micronaut.io/latest/guide/index.html#jsonBinding
jackson:
  serialization:
    indentOutput: true
    writeDatesAsTimestamps: false
  deserialization:
    useBigIntegerForInts: true
    failOnUnknownProperties: false
